FROM 
# ENTRYPOINT [java -jar app.jar --spring.config.location=file:///Users/home/config/application.properties]

# or
export SPRING_CONFIG_NAME=application
export SPRING_CONFIG_LOCATION=file:///hosting/config
java -jar app.jar